// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using NicoPasino.Core.Modelos.MoviesMySql;

namespace NicoPasino.Infra.Data;

public partial class moviesdbContext : DbContext
{
    public moviesdbContext(DbContextOptions<moviesdbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Genre> Genre { get; set; }

    public virtual DbSet<Movie> Movie { get; set; }

    public virtual DbSet<Moviegenres> Moviegenres { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<Genre>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("genre");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Movie>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("movie");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Activo)
                .HasColumnType("bit(1)")
                .HasColumnName("activo");
            entity.Property(e => e.Director)
                .HasMaxLength(255)
                .HasColumnName("director");
            entity.Property(e => e.Duration).HasColumnName("duration");
            entity.Property(e => e.FechaCreacion)
                .HasMaxLength(6)
                .HasColumnName("fechaCreacion");
            entity.Property(e => e.FechaModificacion)
                .HasMaxLength(6)
                .HasColumnName("fechaModificacion");
            entity.Property(e => e.IdPublica).HasColumnName("idPublica");
            entity.Property(e => e.Poster).HasColumnName("poster");
            entity.Property(e => e.Rate)
                .HasPrecision(2, 1)
                .HasColumnName("rate");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("title");
            entity.Property(e => e.Year).HasColumnName("year");
        });

        modelBuilder.Entity<Moviegenres>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("moviegenres");

            entity.HasIndex(e => e.GenreId, "fk_moviegenres_genre");

            entity.HasIndex(e => e.MovieId, "fk_moviegenres_movie");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.GenreId).HasColumnName("genreId");
            entity.Property(e => e.MovieId).HasColumnName("movieId");

            entity.HasOne(d => d.Genre).WithMany(p => p.Moviegenres)
                .HasForeignKey(d => d.GenreId)
                .HasConstraintName("fk_moviegenres_genre");

            entity.HasOne(d => d.Movie).WithMany(p => p.Moviegenres)
                .HasForeignKey(d => d.MovieId)
                .HasConstraintName("fk_moviegenres_movie");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}