// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NicoPasino.Core.Modelos.MoviesMySql;

public partial class Genre
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Moviegenres> Moviegenres { get; set; } = new List<Moviegenres>();
}