// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NicoPasino.Core.Modelos.Notas;

public partial class Cards
{
    public int Id { get; set; }

    public int IdPublica { get; set; }

    public string Header { get; set; }

    public string Text { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime FechaModificacion { get; set; }

    public string Name { get; set; }

    public string Color { get; set; }

    public bool Favorito { get; set; }

    public bool Archivado { get; set; }

    public bool Eliminado { get; set; }
}